// A1 pure indicator kernel — two-oracle evidence (adjudicated 2026-08-22):
//
//   1. PORT-FIDELITY: golden vectors generated by executing the exact
//      re-vetted donor source (atilaahmettaner/tradingview-mcp @ d77db101,
//      indicators_calc.py, sha256-verified) on shared synthetic series.
//      These prove the JS port is faithful to the donor — nothing more.
//   2. CORRECTNESS: independent hand-derived contract fixtures below, each
//      with its derivation written out, so a donor bug cannot be "confirmed"
//      by donor output.
//
// Plus edge-case pins (the approved positive-integer-period delta, warm-up,
// empty/constant inputs, zero-loss RSI branch) and static invariants (the
// kernel imports nothing and nothing in the product surface imports it yet).
import { describe, it, test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { sma, ema, rsi, atr, donchian } from '../src/analytics/indicators.js';

const here = dirname(fileURLToPath(import.meta.url));
const SERIES = JSON.parse(readFileSync(join(here, 'fixtures/analytics/series.json'), 'utf8'));
const VECTORS = JSON.parse(readFileSync(join(here, 'fixtures/analytics/donor-vectors.json'), 'utf8'));

const EPS = 1e-9;
function assertClose(a, b, ctx) {
  if (a === null || b === null) {
    assert.equal(a, b, `${ctx}: null alignment (js=${a}, donor=${b})`);
    return;
  }
  const tol = EPS * Math.max(1, Math.abs(a), Math.abs(b));
  assert.ok(Math.abs(a - b) <= tol, `${ctx}: |${a} - ${b}| > ${tol}`);
}
function assertSeriesClose(actual, expected, ctx) {
  assert.equal(actual.length, expected.length, `${ctx}: length`);
  for (let i = 0; i < expected.length; i++) assertClose(actual[i], expected[i], `${ctx}[${i}]`);
}

// ── 1. port-fidelity: every donor-generated vector case ─────────────────────

describe('port fidelity — donor golden vectors (compatibility oracle only)', () => {
  assert.equal(VECTORS.meta.commit, 'd77db101edc1b57b260450ddda5ca4f7f0211ecd', 'vectors bind to the vetted donor commit');
  for (const c of VECTORS.cases) {
    it(`${c.fn} series=${c.series} period=${c.period}`, () => {
      const s = SERIES[c.series];
      if (c.fn === 'sma') assertSeriesClose(sma(s.closes, c.period), c.out, 'sma');
      else if (c.fn === 'ema') assertSeriesClose(ema(s.closes, c.period), c.out, 'ema');
      else if (c.fn === 'rsi') assertSeriesClose(rsi(s.closes, c.period), c.out, 'rsi');
      else if (c.fn === 'atr') assertSeriesClose(atr(s.highs, s.lows, s.closes, c.period), c.out, 'atr');
      else if (c.fn === 'donchian') {
        const d = donchian(s.highs, s.lows, c.period);
        assertSeriesClose(d.upper, c.out.upper, 'donchian.upper');
        assertSeriesClose(d.lower, c.out.lower, 'donchian.lower');
        assertSeriesClose(d.middle, c.out.middle, 'donchian.middle');
      } else assert.fail(`unknown vector fn ${c.fn}`);
    });
  }
});

// ── 2. independent hand-derived contract vectors (correctness oracle) ───────

describe('independent contract vectors — derivations in comments, no donor involvement', () => {
  it('SMA: [1,2,3,4,5] p=3 → averages 2,3,4 after two-null warm-up', () => {
    // (1+2+3)/3=2, (2+3+4)/3=3, (3+4+5)/3=4
    assert.deepEqual(sma([1, 2, 3, 4, 5], 3), [null, null, 2, 3, 4]);
  });
  it('SMA/EMA at p=len produce exactly one value; p=1 is the identity — round-2 boundary pins', () => {
    // p=len: sma([2,4,8],3) → [(2+4+8)/3]=14/3 at the last index only; the EMA
    // is its seed there (same value). A `<= period` sufficiency mutant would
    // return all-null for both.
    assertSeriesClose(sma([2, 4, 8], 3), [null, null, 14 / 3], 'sma p=len');
    assertSeriesClose(ema([2, 4, 8], 3), [null, null, 14 / 3], 'ema p=len');
    // p=1: k=2/2=1, so EMA(1)=closes; SMA(1)=closes.
    assert.deepEqual(sma([3, 4], 1), [3, 4]);
    assert.deepEqual(ema([3, 4], 1), [3, 4]);
  });
  it('EMA: [2,4,6,8,10] p=3 → seed=SMA(2,4,6)=4; k=0.5; then 8*.5+4*.5=6; 10*.5+6*.5=8', () => {
    assert.deepEqual(ema([2, 4, 6, 8, 10], 3), [null, null, 4, 6, 8]);
  });
  it('EMA vs SMA DISCRIMINATOR: on [2,4,6,10] p=3 they must differ (xcheck round 1 — an arithmetic progression makes them coincide)', () => {
    // EMA: seed=SMA(2,4,6)=4; k=0.5; idx3 = 10*.5 + 4*.5 = 7.
    // SMA: idx3 = (4+6+10)/3 = 20/3 ≈ 6.667. A donor bug implementing EMA as a
    // rolling SMA would have passed the fixture above AND the port-fidelity
    // vectors (shared assumption); this case is the correctness discriminator.
    const e = ema([2, 4, 6, 10], 3);
    const s = sma([2, 4, 6, 10], 3);
    assert.deepEqual(e, [null, null, 4, 7]);
    assertClose(s[3], 20 / 3, 'sma[3]');
    assert.notEqual(e[3], s[3], 'the fixture must actually discriminate EMA from SMA');
  });
  it('RSI p=2 on [10,11,10,11]: window gains [1,0] losses [0,1] → RS=1 → 50; next diff +1 → avgG=.75 avgL=.25 → RS=3 → 75', () => {
    // full-array comparison pins output LENGTH too (round-2: a recurrence
    // bound of `<=` would append a trailing NaN that spot checks miss)
    assertSeriesClose(rsi([10, 11, 10, 11], 2), [null, null, 50, 75], 'rsi mixed');
  });
  it('RSI exact-minimum history (len = period+1) yields exactly one value — round-2 boundary pin', () => {
    // p=2 on [10,11,10]: gains [1,0] avg .5; losses [0,1] avg .5 → RS=1 → 50.
    // A `<= period + 1` sufficiency mutant would return all-null here.
    assertSeriesClose(rsi([10, 11, 10], 2), [null, null, 50], 'rsi boundary');
  });
  it('RSI p=1: per-step Wilder collapses to the last change — round-2 p=1 pin', () => {
    // [5,6,5,5]: +1 → 100; −1 → avgG=0,avgL=1 → 0; 0 → avgG=0,avgL=0 → zero-loss branch → 100.
    assertSeriesClose(rsi([5, 6, 5, 5], 1), [null, 100, 0, 100], 'rsi p=1');
  });
  it('RSI: strictly rising series → 100 everywhere after warm-up (zero-loss branch)', () => {
    const closes = Array.from({ length: 20 }, (_, i) => i + 1);
    const r = rsi(closes, 14);
    for (let i = 14; i < 20; i++) assert.equal(r[i], 100.0);
  });
  it('RSI: strictly falling series → 0 after warm-up (RS=0 → 100-100/1)', () => {
    const closes = Array.from({ length: 20 }, (_, i) => 100 - i);
    const r = rsi(closes, 14);
    for (let i = 14; i < 20; i++) assertClose(r[i], 0, `rsi[${i}]`);
  });
  it('ATR p=1: equals the TR series — gap bar pins the three-term max', () => {
    // bars: C0=10 (H10/L10). bar1 gaps up: H15,L12,C14.
    //   TR1 = max(15-12=3, |15-10|=5, |12-10|=2) = 5  ← |H-prevC| wins (gap)
    // bar2: H14,L8,C9 with prevC=14:
    //   TR2 = max(14-8=6, |14-14|=0, |8-14|=6) = 6    ← H-L wins
    const r = atr([10, 15, 14], [10, 12, 8], [10, 14, 9], 1);
    assert.equal(r[0], null);
    assertClose(r[1], 5, 'atr[1]');
    assertClose(r[2], 6, 'atr[2]');
  });
  it('ATR: each TR branch has a STRICT winner (xcheck round 1 — the original gap bar TIED |L-prevC| with H-L)', () => {
    // Low-side gap strictly wins: prevC=10, H=8, L=6 →
    //   TR = max(8-6=2, |8-10|=2, |6-10|=4) = 4 (a two-term max would give 2).
    assert.deepEqual(atr([10, 8], [10, 6], [10, 7], 1), [null, 4]);
    // High-side gap strictly wins (owner-added): prevC=10, H=14, L=12 →
    //   TR = max(14-12=2, |14-10|=4, |12-10|=2) = 4.
    assert.deepEqual(atr([10, 14], [10, 12], [10, 13], 1), [null, 4]);
    // H=L doji (zero range): prevC=10, H=L=12 →
    //   TR = max(0, 2, 2) = 2 — the gap terms, not H-L, carry a zero-range bar.
    assert.deepEqual(atr([10, 12], [10, 12], [10, 12], 1), [null, 2]);
  });
  it('ATR p=2 hand recurrence: seed=(TR1+TR2)/2, then Wilder', () => {
    // Same bars as above + bar3: H10,L9,C10 with prevC=9 → TR3=max(1,1,0)=1.
    // seed at idx2 = (5+6)/2 = 5.5; idx3 = (5.5*1 + TR3=1)/2 = 3.25
    const r = atr([10, 15, 14, 10], [10, 12, 8, 9], [10, 14, 9, 10], 2);
    assert.deepEqual(r.slice(0, 2), [null, null]);
    assertClose(r[2], 5.5, 'atr[2]');
    assertClose(r[3], 3.25, 'atr[3]');
  });
  it('Donchian at p=len, p=1, and full-channel warm-up — round-2 boundary pins', () => {
    // p=len: one channel at the last index. A `n <= period` early-return
    // mutant would return all-null.
    const pl = donchian([1, 3, 2], [0, 1, -1], 3);
    assert.deepEqual(pl.upper, [null, null, 3]);
    assert.deepEqual(pl.lower, [null, null, -1]);
    assert.deepEqual(pl.middle, [null, null, 1]);
    const p2 = donchian([3, 1], [0, -1], 2);
    assert.deepEqual(p2.upper, [null, 3]);
    assert.deepEqual(p2.lower, [null, -1]);
    assert.deepEqual(p2.middle, [null, 1]);
    // p=1: the channel is the bar itself.
    const p1 = donchian([5, 7], [4, 6], 1);
    assert.deepEqual(p1.upper, [5, 7]);
    assert.deepEqual(p1.lower, [4, 6]);
    assert.deepEqual(p1.middle, [4.5, 6.5]);
    // insufficient history / empty: ALL THREE channels, not just upper
    const short = donchian([1, 2], [1, 2], 3);
    assert.deepEqual(short.upper, [null, null]);
    assert.deepEqual(short.lower, [null, null]);
    assert.deepEqual(short.middle, [null, null]);
    const empty = donchian([], [], 3);
    assert.deepEqual(empty.upper, []);
    assert.deepEqual(empty.lower, []);
    assert.deepEqual(empty.middle, []);
  });
  it('Donchian p=2 INCLUDES the current bar (adjudicated pin — do not "fix" into exclusion)', () => {
    // highs [1,2,3,4], lows [0,1,2,3]:
    // idx1: max(1,2)=2 / min(0,1)=0 ; idx2: max(2,3)=3 / min(1,2)=1 ; idx3: 4/2
    const d = donchian([1, 2, 3, 4], [0, 1, 2, 3], 2);
    assert.deepEqual(d.upper, [null, 2, 3, 4]);
    assert.deepEqual(d.lower, [null, 0, 1, 2]);
    assert.deepEqual(d.middle, [null, 1, 2, 3]);
    // The bar-inclusive definition means a bar can never exceed its own
    // channel — that property belongs to the indicator; whether a strategy
    // may act on it is A1b's contract.
    const flatH = [10, 10, 10, 10, 10];
    const flat = donchian(flatH, flatH, 3);
    for (let i = 2; i < 5; i++) assert.equal(flat.upper[i], 10);
  });
});

// ── 3. edge cases ───────────────────────────────────────────────────────────

describe('edges — approved period delta, warm-up, empty, constant', () => {
  const closes = [1, 2, 3, 4, 5];
  // Infinity added round-2: Math.floor(Infinity) === Infinity, so a
  // floor-equality validator mutant would silently accept it (all-null output).
  const badPeriods = [0, -1, 1.5, '14', NaN, null, Infinity];
  it('invalid periods fail closed on every function (approved ADAPT delta)', () => {
    for (const p of badPeriods) {
      assert.throws(() => sma(closes, p), /positive integer/, `sma(${p})`);
      assert.throws(() => ema(closes, p), /positive integer/, `ema(${p})`);
      assert.throws(() => rsi(closes, p), /positive integer/, `rsi(${p})`);
      assert.throws(() => atr(closes, closes, closes, p), /positive integer/, `atr(${p})`);
      assert.throws(() => donchian(closes, closes, p), /positive integer/, `donchian(${p})`);
    }
  });
  it('insufficient history → all-null (donor semantics)', () => {
    assert.deepEqual(sma([1, 2], 3), [null, null]);
    assert.deepEqual(ema([1, 2], 3), [null, null]);
    assert.deepEqual(rsi([1, 2, 3], 3), [null, null, null]); // needs period+1
    assert.deepEqual(atr([1, 2], [1, 2], [1, 2], 2), [null, null]); // needs period+1
    assert.deepEqual(donchian([1, 2], [1, 2], 3).upper, [null, null]);
  });
  it('empty input → empty outputs, no throw', () => {
    assert.deepEqual(sma([], 3), []);
    assert.deepEqual(ema([], 3), []);
    assert.deepEqual(rsi([], 3), []);
    assert.deepEqual(atr([], [], [], 3), []);
    assert.deepEqual(donchian([], [], 3).upper, []);
  });
  it('constant prices: SMA/EMA = the constant; RSI = 100 (donor zero-loss branch, pinned as characterized); ATR = H-L', () => {
    const flat = new Array(10).fill(50);
    assert.equal(sma(flat, 3)[9], 50);
    assert.equal(ema(flat, 3)[9], 50);
    assert.equal(rsi(flat, 3)[9], 100.0);
    const a = atr(flat.map((c) => c + 1), flat.map((c) => c - 1), flat, 3);
    assertClose(a[9], 2, 'atr flat'); // TR = H-L = 2 every bar
  });
  it('mismatched column lengths refuse loudly (donor raised IndexError; silent NaN would be a semantic change)', () => {
    assert.throws(() => atr([1, 2, 3], [1, 2], [1, 2, 3], 1), /equal lengths/);
    assert.throws(() => donchian([1, 2, 3], [1, 2], 2), /equal lengths/);
    // round-2: the oracle must not be one-shaped — a SHORT closes column and a
    // LONGER column must refuse too (a highs-vs-lows-only or `<`-based
    // validator mutant would accept these).
    assert.throws(() => atr([10, 12], [9, 11], [10], 1), /equal lengths/);
    assert.throws(() => donchian([1, 2], [0, 1, 2], 2), /equal lengths/);
  });
});

// ── 4. static invariants — zero capability, zero product wiring ─────────────

describe('kernel invariants', () => {
  const src = readFileSync(join(here, '../src/analytics/indicators.js'), 'utf8');
  // Capability scan runs over CODE only — comments legitimately DESCRIBE the
  // invariants ("never fetches anything") without invoking anything.
  const code = src.replace(/\/\*[\s\S]*?\*\//g, '').split('\n').filter((l) => !/^\s*\/\//.test(l)).join('\n');
  it('imports nothing and reaches for no capability', () => {
    assert.ok(!/^\s*import /m.test(code), 'no imports at all');
    assert.ok(!/require\(/.test(code), 'no require');
    for (const banned of ['fetch', 'XMLHttpRequest', 'WebSocket', 'process.', 'fs.', 'child_process', 'eval(', 'Function(']) {
      assert.ok(!code.includes(banned), `no ${banned}`);
    }
  });
  it('no MCP/product surface imports the kernel yet (A1: no exposure)', () => {
    const roots = ['../src/server.js', '../src/connection.js', '../src/wait.js'];
    for (const f of readdirSync(join(here, '../src/tools'))) roots.push(`../src/tools/${f}`);
    for (const f of readdirSync(join(here, '../src/core'))) {
      if (f.endsWith('.js')) roots.push(`../src/core/${f}`);
    }
    for (const rel of roots) {
      const text = readFileSync(join(here, rel), 'utf8');
      assert.ok(!text.includes('analytics'), `${rel} must not wire the kernel in A1`);
    }
  });
});

// ── provenance readback (acceptance item 2) ─────────────────────────────────

test('attribution readback: notices file binds donor, SHA, path, MIT, and the approved delta', () => {
  const notices = readFileSync(join(here, '../THIRD_PARTY_NOTICES.md'), 'utf8');
  for (const needle of [
    'atilaahmettaner/tradingview-mcp',
    'd77db101edc1b57b260450ddda5ca4f7f0211ecd',
    'src/tradingview_mcp/core/services/indicators_calc.py',
    'Copyright (c) 2025 Ahmet Taner Atila',
    'MIT',
    'positive integer',
  ]) {
    assert.ok(notices.includes(needle), `notices must contain: ${needle}`);
  }
});
